"""empty message

Revision ID: 8292137642f4
Revises: 77dafa54e5e0
Create Date: 2025-04-02 20:31:00.577037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8292137642f4'
down_revision = '77dafa54e5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
